openapi: 3.0.3
info:
  title: technical-control-ms
  description: Technical control microservice
  version: 1.0.0
servers:
- url: /rest/technical-control-api/v1.0/
paths:
  /get/all-driver-vehicles:
    get:
      tags:
      - Catalogs
      summary: Obtiene todos los conductores
      description: Devuelve todos las conductores de la base
      operationId: get_all_drivers
      parameters:
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /get/all-licenses-vehicles:
    get:
      tags:
      - Catalogs
      summary: Obtiene todos las placas de los vehículos
      description: Devuelve todos los vehiculos de la base
      operationId: get_all_licenses
      parameters:
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /clients:
    get:
      tags:
      - Clients
      summary: Obtiene todos los clientes
      description: Devuelve todos los clientes de la base
      operationId: get_clients
      parameters:
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /location:
    get:
      tags:
      - Location
      summary: Obtiene todos las sucursales de los clientes
      description: Devuelve todos las sucursales de la base
      operationId: get_location
      parameters:
        - name: client_id
          in: query
          required: true
          schema:
            type: string
            example: "1, 2, 3"
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /task:
    get:
      tags:
      - Task
      summary: Obtiene todos las tareas / actividades de los tecnicos
      description: Devuelve todos las tareas / actividades de la base
      operationId: get_task
      parameters:
        - name: locations
          in: query
          required: false
          schema:
            type: string
            example: "1, 2, 3"
        - name: clients
          in: query
          required: false
          schema:
            type: string
            example: "1, 2, 3"
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
    post:
      tags:
      - Task
      summary: Guarda las tareas en la base de datos.
      description: Guardado de tareas de tecnicos
      operationId: post_task
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestPostTask"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /get/all-reasons:
    get:
      tags:
      - Catalogs
      summary: Obtiene todos las razones / motivos
      description: Devuelve todos las razones / motivos de la base
      operationId: get_all_reasons
      parameters:
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /get/all-copilot-vehicles:
    get:
      tags:
      - Catalogs
      summary: Obtiene todos los copilotos de los vehículos
      description: Devuelve todos los copilotos de vehiculos de la base
      operationId: get_all_copilot
      parameters:
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /get/all-projects:
    get:
      tags:
      - Catalogs
      summary: Obtiene todos los proyectos de clientes
      description: Devuelve todos los proyectos de clientes de la base
      operationId: get_all_projects
      parameters:
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /get/all-level-gasoline:
    get:
      tags:
      - Catalogs
      summary: Obtiene todos los niveles de gasolina
      description: Devuelve todos los niveles de gasolina de la base
      operationId: get_all_level_gasoline
      parameters:
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /update/technical-control:
    put:
      tags:
      - Technical
      summary: Actualiza el control tecnico en la base de datos.
      description: Actualiza de control tecnico de ingreso
      operationId: put_technical
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/RequestPutTechnicalControl"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /technical_record:
    get:
      tags:
      - Technical
      summary: Obtiene todos los registros tecnicos
      description: Devuelve todos los registros tecnicos de la base
      operationId: get_tech_record
      parameters:
        - name: locations
          in: query
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
          example: [1,2,3]
        - name: clients
          in: query
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
          example: [1,2,3]
        - name: tasks
          in: query
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
          example: [1,2,3]
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
    post:
      tags:
      - Technical
      summary: Guarda el control tecnico en la base de datos.
      description: Guardado de control tecnico de ingreso
      operationId: post_tech_record
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/RequestPostTechnicalControl"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
  /auditing:
    get:
      tags:
      - Auditing
      summary: Obtiene todos los registros de fiscalizacion
      description: Devuelve todos los registros de fiscalizacion de la base
      operationId: get_auditing
      parameters:
        - name: locations
          in: query
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
          example: [1,2,3]
        - name: clients
          in: query
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
          example: [1,2,3]
        - name: tasks
          in: query
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
          example: [1,2,3]
        - name: externalTransactionId
          in: header
          required: true
          schema:
            type: string
            example: "fcea920f7412b5da7be0cf42b8c93759"
        - name: channel
          in: header
          required: true
          schema:
            type: string
            example: "TECHNICAL_MOVIL"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
    post:
      tags:
      - Auditing
      summary: Guarda la fiscalizacion en la base de datos.
      description: Guardado de fiscalizacion
      operationId: post_auditing
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/RequestPostTechnicalControl"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
      x-openapi-router-controller: swagger_server.controllers.technical_controller.TechnicalView
components:
  schemas:
    RequestPostTechnicalControl:
      properties:
        technical_data:
          $ref: "#/components/schemas/TechnicalData"
        channel:
          type: string
          example: Tech control
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
    RequestPutTechnicalControl:
      properties:
        technical_data:
          $ref: "#/components/schemas/TechnicalPutData"
        channel:
          type: string
          example: Tech control
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
    RequestPostTask:
      properties:
        technical_data:
          $ref: "#/components/schemas/TaskData"
        channel:
          type: string
          example: Tech control
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
    TechnicalData:
      type: object
      properties:
        materials:
          type: array
          items:
            $ref: "#/components/schemas/MaterialsData"
        task_id:
          type: integer
          example: 1
        client_id:
          type: integer
          example: 1
        location_id:
          type: integer
          example: 1
        resume:
          type: string
          example: "1"
        user:
          type: string
          example: "dmales"
        images:
          maxItems: 10
          type: array
          items:
            type: string
            format: binary
    MaterialsData:
      type: object
      properties:
        quantity:
          type: integer
          example: 1
        material:
          type: string
          example: "1"
    TechnicalPutData:
      type: object
      properties:
        id_movilization:
          type: integer
          example: 1
          nullable: false
        final_gasoline_id:
          type: integer
          example: 2
        final_km:
          type: string
          example: "1"
        have_incident:
          type: boolean
          example: true
        detail_incident:
          type: string
          example: "N/A"
        exit_date:
          type: string
          example: 2022-02-03 13:58:00
        final_images:
          maxItems: 10
          type: array
          items:
            type: string
            format: binary
      example:
        id_movilization: 4
        final_gasoline_id: 4
        final_km: "155"
        have_incident: true
        detail_incident: "N/A"
        exit_date: "2022-02-03 13:58:00"
        final_images: []
    GenericResponse:
      properties:
        data:
          type: object
          nullable: true
          example: Estructura generica.
        errorCode:
          type: integer
          example: 0
        message:
          type: string
          example: Mensaje generico.
        internalTransactionId:
          type: string
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
      example:
        errorCode: 0
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Mensaje generico.
        data: {}
    DriverCompanion:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/DriverCompanionData"
      example:
        data:
        - id_reason: 1
          reason: Trabajo programado
        - id_reason: 2
          reason: Razon
    DriverCompanionData:
      type: object
      properties:
        id_driver_companion:
          type: integer
          example: 1
        name:
          type: string
          example: Daniel
      example:
        id_driver_companion: 1
        name: Daniel
    Reasons:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/ReasonsData"
      example:
        data:
        - id_reason: 1
          reason: Trabajo programado
        - id_reason: 2
          reason: Razon
    ReasonsData:
      type: object
      properties:
        id_reason:
          type: integer
          example: 1
        reason:
          type: string
          example: Trabajo programado
      example:
        id_reason: 1
        reason: Trabajo programado
    Project:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/ProjectsData"
      example:
        data:
        - id_project: 1
          name: Expalsa
        - id_project: 2
          name: Biomar
    ProjectsData:
      type: object
      properties:
        id_project:
          type: integer
          example: 1
        name:
          type: string
          example: Expalsa
      example:
        id_project: 1
        name: Trabajo programado
    TaskData:
      type: object
      properties:
        location_id:
          type: integer
          example: 1
        name:
          type: string
          example: "TAREA INSTALACION"
        description:
          type: string
          example: "N/A"
        code:
          type: string
          example: "TASK-TEST-001"
        user:
          type: string
          example: "dmales"
    ResponseError:
      type: object
      properties:
        errorCode:
          type: integer
        internalTransactionId:
          type: string
        externalTransactionId:
          type: string
        message:
          type: string
    RequestGeneric:
      properties:
        channel:
          type: string
          example: ZENTINEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c9375

